version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: routewise-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: routewise
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - routewise-network

  # Redis Cache (Optional)
  redis:
    image: redis:7.2-alpine
    container_name: routewise-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - routewise-network

  # Backend API
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: routewise-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/routewise?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-this-in-production
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./apps/api/uploads:/app/uploads
    networks:
      - routewise-network

  # Frontend Web App (B2C - Customers)
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: routewise-web
    restart: unless-stopped
    ports:
      - "3010:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3010
      NEXTAUTH_SECRET: your-nextauth-secret-key-change-this-in-production
    depends_on:
      - api
    networks:
      - routewise-network

  # Admin App (B2B - Operators)
  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    container_name: routewise-admin
    restart: unless-stopped
    ports:
      - "3020:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3020
      NEXTAUTH_SECRET: your-nextauth-secret-key-change-this-in-production
    depends_on:
      - api
    networks:
      - routewise-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: routewise-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
      - admin
      - api
    networks:
      - routewise-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  routewise-network:
    driver: bridge
